version: "3"

services:
  app:
    build: .
    env_file:
      - .env
    user: "${UID}:${GID}"
    container_name: ma_dev
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
      - "/app/node_modules"
