const path = require("path");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const RemoveEmptyScriptsPlugin = require("webpack-remove-empty-scripts");

module.exports = (env, argv) => {
  return {
    stats: 'minimal',
    plugins: [
      new RemoveEmptyScriptsPlugin(), // Removing empty script generated by scss file
      new MiniCssExtractPlugin({
        filename: "../css/modal-actions.min.css",
      }),
    ],
    optimization: {
      removeEmptyChunks: true,
    },
    mode: argv.mode,
    entry: {
      "modal-actions": "./src/index.js",
      style: "./src/assets/scss/main.scss",
    },
    output: {
      filename: "[name].min.js",
      path: path.resolve(__dirname, "dist"),
      library: "ModalActions",
      libraryTarget: "umd",
      libraryExport: "ModalActions",
      umdNamedDefine: true,
    },
    module: {
      rules: [
        {
          test: /\.s[ac]ss$/i,
          use: [
            MiniCssExtractPlugin.loader,
            "css-loader", // Translates CSS into CommonJS
            "sass-loader", // Compiles Sass to CSS
          ],
        },
      ],
    },
  };
};
